Repository qdrant/qdrant-web-ui, pull requests merged in 2023-08, with the labels that each got.

#95 Point images fix - removed the wrong condition
  src/components/Points/PointCard.jsx
Labels: bug

#99 history local storage quota overflow fixed
  src/components/CodeEditorWindow/config/RequesFromCode.js
Labels: bug

#105 API key in snapshot upload request
  src/components/Snapshots/SnapshotUploadForm.jsx
Labels: bug

#103 Collection info tab
  .eslintrc.yml
  src/components/Collections/CollectionCluster/ClusterInfo.jsx
  src/components/Collections/CollectionCluster/ClusterInfoHead.jsx
  src/components/Collections/CollectionCluster/ClusterShardRow.jsx
  src/components/Collections/CollectionCluster/collectionCluster.test.jsx
  src/components/Collections/CollectionInfo.jsx
  src/components/Common/Dot.jsx
  src/components/Points/DataGridList.jsx
  src/components/Points/PointCard.jsx
  src/components/Points/PointPayloadList.jsx
  src/components/VisualizeChart/ViewPointModal.jsx
  src/pages/Collection.jsx
  src/setupTests.js
  src/theme/index.js
Labels: enhancement

#107 Download snapshot with api key + refactoring
  src/common/client.js
  src/common/client.test.js
  src/common/urils.test.js
  src/common/utils.js
  src/components/CodeEditorWindow/config/RequesFromCode.js
  src/components/CodeEditorWindow/index.jsx
  src/components/Common/CircularProgressWithLabel.jsx
  src/components/Snapshots/SnapshotUploadForm.jsx
  src/components/Snapshots/SnapshotsTab.jsx
  src/components/Snapshots/SnapshotsTableRow.jsx
  src/components/VisualizeChart/index.jsx
Labels: bug, enhancement
